project_id = "mdwwoaqykjghbfywtkof"

[functions.send-auth-email]
verify_jwt = false

[functions.custom-signup]
verify_jwt = false

[functions.send-introduction-email]
verify_jwt = false

[functions.chatbot]
verify_jwt = false